version: '3.1'

services:
  database:
    image: postgres # use latest official postgres version
    container_name: postgresdb
    restart: always
    env_file:
      - ../database.env # configure postgres
    ports:
      # <Port exposed> : < Postgres Port running inside container>
      - 5434:5432
